interpl = Drive.where(power: 0, military: false).first_or_create(mass:   4)
class_1 = Drive.where(power: 1, military: false).first_or_create(mass:  10)
class_2 = Drive.where(power: 2, military: false).first_or_create(mass:  25)
class_3 = Drive.where(power: 3, military: false).first_or_create(mass:  45)
class_4 = Drive.where(power: 4, military: false).first_or_create(mass:  80)
class_5 = Drive.where(power: 5, military: false).first_or_create(mass: 150)
class_6 = Drive.where(power: 6, military: false).first_or_create(mass: 250)
class_7 = Drive.where(power: 7, military: false).first_or_create(mass: 400)
class_8 = Drive.where(power: 8, military: false).first_or_create(mass: 600)
milit_1 = Drive.where(power: 1, military: true ).first_or_create(mass:   6)
milit_2 = Drive.where(power: 2, military: true ).first_or_create(mass:  12)
milit_3 = Drive.where(power: 3, military: true ).first_or_create(mass:  24)

Ship.where(name: 'Interplanetary Shuttle').first_or_create(capacity:    4, mass:    8, guns: 0, missiles: 0, crew:  1, acceleration:  5.0, deceleration:  3.0, default_drive: interpl)
Ship.where(name: 'Lifter'                ).first_or_create(capacity:    7, mass:   10, guns: 0, missiles: 0, crew:  1, acceleration:  4.0, deceleration:  2.0, default_drive: interpl)
Ship.where(name: 'Falcon attack fighter' ).first_or_create(capacity:   11, mass:   16, guns: 1, missiles: 2, crew:  1, acceleration: 30.2, deceleration:  9.0, default_drive: milit_1)
Ship.where(name: 'Eagle Mk2 fighter'     ).first_or_create(capacity:   22, mass:   28, guns: 1, missiles: 2, crew:  1, acceleration: 28.2, deceleration:  4.0, default_drive: class_1)
Ship.where(name: 'Adder'                 ).first_or_create(capacity:   40, mass:   55, guns: 1, missiles: 0, crew:  1, acceleration: 18.1, deceleration:  8.0, default_drive: class_2)
Ship.where(name: 'Viper Defence Craft'   ).first_or_create(capacity:   50, mass:   65, guns: 1, missiles: 4, crew:  1, acceleration: 24.2, deceleration: 10.0, default_drive: class_2)
Ship.where(name: 'Cobra Mark I'          ).first_or_create(capacity:   60, mass:   75, guns: 2, missiles: 2, crew:  1, acceleration: 16.1, deceleration:  6.0, default_drive: class_2)
Ship.where(name: 'Cobra Mk III'          ).first_or_create(capacity:   80, mass:  100, guns: 2, missiles: 4, crew:  1, acceleration: 20.1, deceleration:  7.0, default_drive: class_2)
Ship.where(name: 'Constrictor'           ).first_or_create(capacity:   90, mass:  120, guns: 2, missiles: 2, crew:  2, acceleration: 22.2, deceleration: 10.0, default_drive: class_2)
Ship.where(name: 'Asp Explorer'          ).first_or_create(capacity:  120, mass:  150, guns: 2, missiles: 1, crew:  2, acceleration: 22.2, deceleration:  7.0, default_drive: class_3)
Ship.where(name: 'Transporter'           ).first_or_create(capacity:  160, mass:  200, guns: 3, missiles: 2, crew:  3, acceleration:  9.0, deceleration:  4.0, default_drive: class_3)
Ship.where(name: 'Lion Transport'        ).first_or_create(capacity:  235, mass:  300, guns: 3, missiles: 8, crew:  4, acceleration:  5.0, deceleration:  3.0, default_drive: class_3)
Ship.where(name: 'Tiger Trader'          ).first_or_create(capacity:  320, mass:  400, guns: 3, missiles: 1, crew:  5, acceleration: 12.1, deceleration:  5.0, default_drive: class_4)
Ship.where(name: 'Puma Clipper'          ).first_or_create(capacity:  825, mass: 1000, guns: 4, missiles: 8, crew:  9, acceleration:  6.0, deceleration:  3.0, default_drive: class_6)
Ship.where(name: 'Panther Clipper'       ).first_or_create(capacity: 2000, mass: 1775, guns: 4, missiles: 8, crew: 12, acceleration:  6.0, deceleration:  3.0, default_drive: class_8)

Upgrade.where(name: 'Auto Refueller'           ).first_or_create(mass:   1)
Upgrade.where(name: 'Atmospheric Shielding'    ).first_or_create(mass:   1)
Upgrade.where(name: 'Laser Cooling Booster'    ).first_or_create(mass:   1)
Upgrade.where(name: 'Cargo Bay Life Support'   ).first_or_create(mass:   1)
Upgrade.where(name: 'Scanner'                  ).first_or_create(mass:   1)
Upgrade.where(name: '1MW Pulse Laser'          ).first_or_create(mass:   1)
Upgrade.where(name: 'Radar Mapper'             ).first_or_create(mass:   1)
Upgrade.where(name: 'E.C.M. System'            ).first_or_create(mass:   2)
Upgrade.where(name: 'Automatic Pilot'          ).first_or_create(mass:   1)
Upgrade.where(name: 'Hyperspace Cloud Analyser').first_or_create(mass:   1)
Upgrade.where(name: 'Shield Generator'         ).first_or_create(mass:   4)
Upgrade.where(name: '5MW Pulse Laser'          ).first_or_create(mass:   3)
Upgrade.where(name: 'Fuel Scoop'               ).first_or_create(mass:   6)
Upgrade.where(name: 'Cargo Scoop Conversion'   ).first_or_create(mass:   2)
Upgrade.where(name: 'MB4 Mining Machine'       ).first_or_create(mass:  30)
Upgrade.where(name: '1MW Beam Laser'           ).first_or_create(mass:   5)
Upgrade.where(name: 'Energy Booster Unit'      ).first_or_create(mass:   5)
Upgrade.where(name: '30MW Mining Laser'        ).first_or_create(mass:  10)
Upgrade.where(name: '4MW Beam Laser'           ).first_or_create(mass:  20)
Upgrade.where(name: 'Naval E.C.M. System'      ).first_or_create(mass:   2)
Upgrade.where(name: 'Hull Auto-Repair System'  ).first_or_create(mass:  40)
Upgrade.where(name: 'Energy Bomb'              ).first_or_create(mass:   4)
Upgrade.where(name: 'Escape Capsule'           ).first_or_create(mass:   5)
Upgrade.where(name: '20MW Beam Laser'          ).first_or_create(mass:  75)
Upgrade.where(name: '100MW Beam Laser'         ).first_or_create(mass: 200)
Upgrade.where(name: 'Small Plasma Accelerator' ).first_or_create(mass: 500)
Upgrade.where(name: 'Large Plasma Accelerator' ).first_or_create(mass: 900)

ross_154      = System.where(name: 'Ross 154',      x: -1.15, y: -0.3 ).first_or_create
barnards_star = System.where(name: 'Barnards Star', x: -0.7,  y:  0.15).first_or_create

merlin = ross_154.planets.where(code: '2a').first_or_create(name: 'Merlin', atmosphere: true)
merlin.settlements.where(name: 'Sirocco Station').first_or_create(settlement_type: Settlement::SURFACE)

cooke = barnards_star.planets.where(code: '1').first_or_create(name: 'Cooke',           atmosphere: nil)
bmwld = barnards_star.planets.where(code: '2').first_or_create(name: 'Birminghamworld', atmosphere: nil)
cooke.settlements.where(name: 'Griffiths Base').first_or_create(settlement_type: Settlement::SURFACE)
cooke.settlements.where(name: 'Miller Depot'  ).first_or_create(settlement_type: Settlement::ORBITAL)
bmwld.settlements.where(name: 'Anderton Depot').first_or_create(settlement_type: Settlement::SURFACE)
bmwld.settlements.where(name: 'Boston Base'   ).first_or_create(settlement_type: Settlement::ORBITAL)

Route.where(system1: ross_154, system2: barnards_star).first_or_create(distance: 5.42)

ross_154.stocks.where(name: Stock::WATER           ).first_or_create(import_export: Stock::MINOR_EXPORT, cost:    1.0)
ross_154.stocks.where(name: Stock::LIQUID_OXYGEN   ).first_or_create(import_export: Stock::MINOR_EXPORT, cost:    8.8)
ross_154.stocks.where(name: Stock::GRAIN           ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:   44.3)
ross_154.stocks.where(name: Stock::FRUIT_AND_VEG   ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:  126.4)
ross_154.stocks.where(name: Stock::ANIMAL_MEAT     ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   94.5)
ross_154.stocks.where(name: Stock::SYNTHETIC_MEAT  ).first_or_create(import_export: nil,                 cost:   20.1)
ross_154.stocks.where(name: Stock::LIQUOR          ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:  428.1)
ross_154.stocks.where(name: Stock::MEDICINES       ).first_or_create(import_export: nil,                 cost:  577.2)
ross_154.stocks.where(name: Stock::FERTILIZER      ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:   15.8)
ross_154.stocks.where(name: Stock::ANIMAL_SKINS    ).first_or_create(import_export: Stock::MINOR_EXPORT, cost:  676.3)
ross_154.stocks.where(name: Stock::LUXURY_GOODS    ).first_or_create(import_export: Stock::MINOR_IMPORT, cost: 1541.4)
ross_154.stocks.where(name: Stock::HEAVY_PLASTICS  ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:   39.6)
ross_154.stocks.where(name: Stock::METAL_ALLOYS    ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:   27.3)
ross_154.stocks.where(name: Stock::PRECIOUS_METALS ).first_or_create(import_export: nil,                 cost: 1712.5)
ross_154.stocks.where(name: Stock::GEM_STONES      ).first_or_create(import_export: nil,                 cost: 3098.7)
ross_154.stocks.where(name: Stock::MINERALS        ).first_or_create(import_export: nil,                 cost:    6.8)
ross_154.stocks.where(name: Stock::HYDROGEN_FUEL   ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:   11.5)
ross_154.stocks.where(name: Stock::MILITARY_FUEL   ).first_or_create(import_export: nil,                 cost:   49.4)
ross_154.stocks.where(name: Stock::INDUSTRIAL_PARTS).first_or_create(import_export: Stock::MINOR_IMPORT, cost:  133.7)
ross_154.stocks.where(name: Stock::COMPUTERS       ).first_or_create(import_export: nil,                 cost:  444.3)
ross_154.stocks.where(name: Stock::AIR_PROCESSORS  ).first_or_create(import_export: nil,                 cost:  204.1)
ross_154.stocks.where(name: Stock::FARM_MACHINERY  ).first_or_create(import_export: nil,                 cost:   75.9)
ross_154.stocks.where(name: Stock::ROBOTS          ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:  887.0)
ross_154.stocks.where(name: Stock::RADIOACTIVES    ).first_or_create(import_export: nil,                 cost:   -4.3)
ross_154.stocks.where(name: Stock::RUBBISH         ).first_or_create(import_export: nil,                 cost:   -0.7)
ross_154.stocks.where(name: Stock::NARCOTICS       ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)
ross_154.stocks.where(name: Stock::LIVE_ANIMALS    ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)
ross_154.stocks.where(name: Stock::SLAVES          ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)
ross_154.stocks.where(name: Stock::HAND_WEAPONS    ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)
ross_154.stocks.where(name: Stock::BATTLE_WEAPONS  ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)
ross_154.stocks.where(name: Stock::NERVE_GAS       ).first_or_create(import_export: Stock::ILLEGAL,      cost:    nil)

barnards_star.stocks.where(name: Stock::WATER           ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:    0.9)
barnards_star.stocks.where(name: Stock::LIQUID_OXYGEN   ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:   11.3)
barnards_star.stocks.where(name: Stock::GRAIN           ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:   47.8)
barnards_star.stocks.where(name: Stock::FRUIT_AND_VEG   ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:  125.8)
barnards_star.stocks.where(name: Stock::ANIMAL_MEAT     ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:  174.3)
barnards_star.stocks.where(name: Stock::SYNTHETIC_MEAT  ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   16.8)
barnards_star.stocks.where(name: Stock::LIQUOR          ).first_or_create(import_export: Stock::MINOR_IMPORT, cost:  425.5)
barnards_star.stocks.where(name: Stock::MEDICINES       ).first_or_create(import_export: Stock::MINOR_EXPORT, cost:  520.0)
barnards_star.stocks.where(name: Stock::FERTILIZER      ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   12.9)
barnards_star.stocks.where(name: Stock::NARCOTICS       ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1249.0)
barnards_star.stocks.where(name: Stock::ANIMAL_SKINS    ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1627.7)
barnards_star.stocks.where(name: Stock::LUXURY_GOODS    ).first_or_create(import_export: Stock::MINOR_IMPORT, cost: 1469.7)
barnards_star.stocks.where(name: Stock::HEAVY_PLASTICS  ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   29.4)
barnards_star.stocks.where(name: Stock::METAL_ALLOYS    ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   20.0)
barnards_star.stocks.where(name: Stock::PRECIOUS_METALS ).first_or_create(import_export: nil,                 cost: 1698.6)
barnards_star.stocks.where(name: Stock::GEM_STONES      ).first_or_create(import_export: nil,                 cost: 2997.7)
barnards_star.stocks.where(name: Stock::MINERALS        ).first_or_create(import_export: Stock::MAJOR_IMPORT, cost:    7.4)
barnards_star.stocks.where(name: Stock::HYDROGEN_FUEL   ).first_or_create(import_export: nil,                 cost:    9.8)
barnards_star.stocks.where(name: Stock::MILITARY_FUEL   ).first_or_create(import_export: nil,                 cost:   48.4)
barnards_star.stocks.where(name: Stock::INDUSTRIAL_PARTS).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:  101.2)
barnards_star.stocks.where(name: Stock::COMPUTERS       ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:  345.0)
barnards_star.stocks.where(name: Stock::AIR_PROCESSORS  ).first_or_create(import_export: nil,                 cost:  194.4)
barnards_star.stocks.where(name: Stock::FARM_MACHINERY  ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:   63.5)
barnards_star.stocks.where(name: Stock::ROBOTS          ).first_or_create(import_export: Stock::MAJOR_EXPORT, cost:  554.3)
barnards_star.stocks.where(name: Stock::RADIOACTIVES    ).first_or_create(import_export: nil,                 cost:   -4.2)
barnards_star.stocks.where(name: Stock::RUBBISH         ).first_or_create(import_export: nil,                 cost:   -0.6)
barnards_star.stocks.where(name: Stock::LIVE_ANIMALS    ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1984.2)
barnards_star.stocks.where(name: Stock::SLAVES          ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1973.1)
barnards_star.stocks.where(name: Stock::HAND_WEAPONS    ).first_or_create(import_export: Stock::ILLEGAL,      cost:  983.6)
barnards_star.stocks.where(name: Stock::BATTLE_WEAPONS  ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1185.9)
barnards_star.stocks.where(name: Stock::NERVE_GAS       ).first_or_create(import_export: Stock::ILLEGAL,      cost: 1564.8)
